export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_SUCC = 'LOGIN_SUCC'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT = 'LOGOUT'

export const SITES_GET_LIST_PENDING = 'SITES_GET_LIST_PENDING'
export const SITES_GET_LIST_SUCC = 'SITES_GET_LIST_SUCC'
export const SITES_GET_LIST_FAIL = 'SITES_GET_LIST_FAIL'
